-- MySQL Script generated by MySQL Workbench
-- Thu Apr  4 21:18:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema commissionsAdminDb
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `commissionsAdminDb`;

-- -----------------------------------------------------
-- Schema commissionsAdminDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `commissionsAdminDb` DEFAULT CHARACTER SET utf8 ;
USE `commissionsAdminDb` ;

-- -----------------------------------------------------
-- Table `commissionsAdminDb`.`Faculty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commissionsAdminDb`.`Faculty` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commissionsAdminDb`.`Career`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commissionsAdminDb`.`Career` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `id_faculty` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_CAREER_FACULTY_idx` (`id_faculty` ASC) VISIBLE,
  CONSTRAINT `FK_CAREER_FACULTY`
    FOREIGN KEY (`id_faculty`)
    REFERENCES `commissionsAdminDb`.`Faculty` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commissionsAdminDb`.`Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commissionsAdminDb`.`Subject` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `id_career` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `FK_SUBJECT_CAREER_idx` (`id_career` ASC) VISIBLE,
  CONSTRAINT `FK_SUBJECT_CAREER`
    FOREIGN KEY (`id_career`)
    REFERENCES `commissionsAdminDb`.`Career` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commissionsAdminDb`.`Semester`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commissionsAdminDb`.`Semester` (
  `id` CHAR(1) NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commissionsAdminDb`.`Professorship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commissionsAdminDb`.`Professorship` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `id_subject` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_PROFSHIP_SUBJECT_idx` (`id_subject` ASC) VISIBLE,
  CONSTRAINT `FK_PROFSHIP_SUBJECT`
    FOREIGN KEY (`id_subject`)
    REFERENCES `commissionsAdminDb`.`Subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commissionsAdminDb`.`Timeshift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commissionsAdminDb`.`Timeshift` (
  `id` CHAR(1) NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commissionsAdminDb`.`Commission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commissionsAdminDb`.`Commission` (
  `id` INT NOT NULL,
  `year` VARCHAR(45) NOT NULL,
  `id_semester` CHAR(1) NOT NULL,
  `id_professorship` INT NOT NULL,
  `id_timeshift` CHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_semester_idx` (`id_semester` ASC) VISIBLE,
  INDEX `FK_COMMISS_PROFSHIP_idx` (`id_professorship` ASC) VISIBLE,
  INDEX `FK_COMMISS_TIMESHIFT_idx` (`id_timeshift` ASC) VISIBLE,
  CONSTRAINT `FK_COMMISS_SEMESTER`
    FOREIGN KEY (`id_semester`)
    REFERENCES `commissionsAdminDb`.`Semester` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_COMMISS_PROFSHIP`
    FOREIGN KEY (`id_professorship`)
    REFERENCES `commissionsAdminDb`.`Professorship` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_COMMISS_TIMESHIFT`
    FOREIGN KEY (`id_timeshift`)
    REFERENCES `commissionsAdminDb`.`Timeshift` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commissionsAdminDb`.`StudentSituation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commissionsAdminDb`.`StudentSituation` (
  `id` CHAR(1) NOT NULL,
  `name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commissionsAdminDb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commissionsAdminDb`.`Student` (
  `id` INT NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `commissionsAdminDb`.`CommissionStudent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `commissionsAdminDb`.`CommissionStudent` (
  `id` INT NOT NULL,
  `finalscore` FLOAT(3,1) NULL,
  `id_studentsituation` CHAR(1) NOT NULL,
  `id_commission` INT NOT NULL,
  `id_student` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_COMMSTU_STUCOND_idx` (`id_studentsituation` ASC) VISIBLE,
  INDEX `FK_COMMSTU_STUDENT_idx` (`id_student` ASC) VISIBLE,
  INDEX `FK_COMMSTU_COMMISS_idx` (`id_commission` ASC) VISIBLE,
  CONSTRAINT `FK_COMMSTU_STUDENT`
    FOREIGN KEY (`id_student`)
    REFERENCES `commissionsAdminDb`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_COMMSTU_STUCOND`
    FOREIGN KEY (`id_studentsituation`)
    REFERENCES `commissionsAdminDb`.`StudentSituation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_COMMSTU_COMMISS`
    FOREIGN KEY (`id_commission`)
    REFERENCES `commissionsAdminDb`.`Commission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
